name: omnivods
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    x-develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:
    - "5173:5173"
    # volumes:
    # - ./:/app
  postgres:
    container_name: postgres-db
    image: postgres:latest
    ports:
    - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - postgres:/var/lib/postgresql/data
volumes:
  app:
    driver: local
  postgres:
    driver: local
  